### ISSUE TITLE
Download of CEL files

### ISSUE THREAD

**Issue by ghost** [CLINDA-AAU/hemaClass#19]
I have added a button to download the .CEL files that is included in the package. But i have not yet added a path to the .CEL files, so be aware that this function doesn't work properly yet.

**Comment by mboegsted** [comment]
I tried it today and the downloaded is empty, is difficult to zip the 4 .Cellfiles and place them somewhere?

**Comment by ghost** [comment]
No thats not a problem. I just had a minor issue with making the download work from both the website and when running it locally. But I should be able to fix that at some point, just haven't had the time to do it yet.

**Comment by mboegsted** [comment]
I still have problem with this using both Safari and Chrome on my Mac. Will try explorer, when I get to work.

**Comment by AEBilgrau** [comment]
It's because is not fixed yet. Will try today.

**Comment by AEBilgrau** [comment]
Now works as per commit 1d47e313d60b407ccb9cf4e5dddadd3e3b25e307.

**Comment by mboegsted** [comment]
I have tried to download the package from github -- it does not seem to work.

**Comment by mboegsted** [comment]
I have tried to download the package from github -- it does not seem to work.

**Comment by mboegsted** [comment]
Arhh, it woks on the homepage, but not locally
