### ISSUE TITLE
Shinyalerts are not shown on the server

### ISSUE THREAD

**Issue by ghost** [CLINDA-AAU/hemaClass#23]
After updating the website, the shinyalerts are not shown anymore.

**Comment by AEBilgrau** [comment]
_Maybe_ it has something to do with using `showshinyalert` vs `shinyalert`. Perhaps a new "updated" interface to in `shinysky`.

**Comment by ghost** [comment]
Yes that sounds plausible. I just updated shinysky on my own computer, and it seems to mess with the warnings

**Comment by falgreen** [comment]
We should probably implement the shinysky functionality directly in the package. This seem to be a recurring problem.

**Comment by AEBilgrau** [comment]
[Oops, replied to the wrong mail before, now deleted.]

Or install from a particular commit hash. (So we don't always use the latest on their development branch.)

I.e. something like:

``` R
devtools::install_github(AnalytixWare/ShinySky, ref = "15c29bec4e7c5e694625e571656515a8ace7f376")
```

Or we should make our own fork for ShinySky on oncoclass?

Probably, we should do the same for hemaClass too. (But here we can use tags.)

**Comment by falgreen** [comment]
It does seem to be a good alternative

Sendt fra min iPhone

> Den 9. okt. 2015 kl. 14.52 skrev Anders Ellern Bilgrau notifications@github.com:
> 
> [Oops, replyed to the wrong mail.]
> 
> Or install from a particular commit hash. (So we don't always use the latest on their development branch.)
> 
> I.e. something like:
> 
> ``` R
> devtools::install_github(AnalytixWare/ShinySky, ref = "15c29bec4e7c5e694625e571656515a8ace7f376")
> ```
> 
> Or we should make our own fork for ShinySky on oncoclass?
> 
> Probably, we should do the same for hemaClass too. (But here we can use tags.)
>

**Comment by AEBilgrau** [comment]
Then again. Shinysky haven't been updated since February.  So it's not changing versions hereof. Probably, we're just doing something stupid.

**Comment by ghost** [comment]
Fixed.
