### ISSUE TITLE
OS and PFS

### ISSUE THREAD

**Issue by mboegsted** [CLINDA-AAU/hemaClass#25]
Should PFS and OS header be changed in patient summaries?

**Comment by AEBilgrau** [comment]
It doesn't look like OS and PFS has been accidentally interchanged in the [code.](https://github.com/oncoclass/hemaClass/blob/master/inst/website/server.R#L1127-L1186)

**Comment by mboegsted** [comment]
I agree -- I took a carefull look at PFS, it decreases faster but levels more fastly off. Meaning that dead is competing risk for progression. However, difficult to understand for laymen :)
