### ISSUE TITLE
Cohorte normalization

### ISSUE THREAD

**Issue by mboegsted** [CLINDA-AAU/hemaClass#28]
When performing cohort-normalization is that just plain RMA equivalent to e.g. just.rma?

**Comment by falgreen** [comment]
Yes, that is equivalent to just.rma

**Comment by mboegsted** [comment]
Do you use just.rma or do you piece to-gether with own functions?

**Comment by AEBilgrau** [comment]
Our own functions.

**Comment by falgreen** [comment]
I piece it together using our own functions.

**Comment by AEBilgrau** [comment]
Or install from a particular commit hash. (So we don't always use the latest on their development branch.)

I.e. something like:

```R
devtools::install_github(AnalytixWare/ShinySky, ref = "15c29bec4e7c5e694625e571656515a8ace7f376")
```

Or we should make our own fork for ShinySky on oncoclass?

Probably, we should do the same for hemaClass too. (But here we can use tags.)
