### ISSUE TITLE
Build reference

### ISSUE THREAD

**Issue by ghost** [CLINDA-AAU/hemaClass#3]
Write a warning when only one .CEL file is uploaded when building a reference, and when the uploaded reference file is not of type .rds

**Comment by falgreen** [comment]
I think this is a good idea. Since the performance is not documented for a reference sample smaller than 30, I think a warning is also appropriate when less than 30 cel files are uploaded.

**Comment by ghost** [comment]
I have added the warning. It shows if there is uploaded less than 30 CEL files.
