### ISSUE TITLE
Disclaimer on survival analysis 

### ISSUE THREAD

**Issue by mboegsted** [CLINDA-AAU/hemaClass#30]
This should be done with a footnote explaining calculations and shortcommings.

**Comment by AEBilgrau** [comment]
Now added. Martin, please correct in file [/inst/website/www/SurvivalCurvesNote.html](https://github.com/oncoclass/hemaClass/blob/master/inst/website/www/SurvivalCurvesNote.html).

**Comment by mboegsted** [comment]
I have read it and made some corrections. I suggest we refer to the paper for more details. In the paper, I suggest we to write a bit more details.
