### ISSUE TITLE
Warning upon library request

### ISSUE THREAD

**Issue by mboegsted** [CLINDA-AAU/hemaClass#36]
Just reloaded and build hemaClass on my MAC and got this error:

> library(hemaClass)
> Warning messages:
> 1: In .recacheSubclasses(def@className, def, doSubclasses, env) :
>   undefined subclass "externalRefMethod" of class "expressionORfunction"; definition not updated
> 2: In .recacheSubclasses(def@className, def, doSubclasses, env) :
>   undefined subclass "externalRefMethod" of class "functionORNULL"; definition not updated

**Comment by AEBilgrau** [comment]
This was a spurious error from the Rstudio environment unrelated to hemaClass. Restart of Rstudio fixed it.
