### ISSUE TITLE
Error in patient summaries

### ISSUE THREAD

**Issue by mboegsted** [CLINDA-AAU/hemaClass#37]
Just ran runHemaClass() on my MAC and got the following error under patient summaries:

undefined columns selected
undefined columns selected

**Comment by AEBilgrau** [comment]
`sessionInfo()`, please? :)

**Comment by mboegsted** [comment]
same problem on hemaclass.org

**Comment by mboegsted** [comment]
Here you go:

> sessionInfo()
> R version 3.2.0 (2015-04-16)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.10.5 (Yosemite)

locale:
[1] da_DK.UTF-8/da_DK.UTF-8/da_DK.UTF-8/C/da_DK.UTF-8/da_DK.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.0

**Comment by AEBilgrau** [comment]
Should now be fixed. Server updated to v1.0.3.
