### ISSUE TITLE
Disclaimer not shown in Microsoft Edge

### ISSUE THREAD

**Issue by AEBilgrau** [CLINDA-AAU/hemaClass#58]
Hi all. FYI, the pop-up disclaiming the site usage does not appear in the Microsoft Edge browser. Everything is grayed out, but no message is shown and thus it cannot be dismissed. This renders the site unusable.

**Comment by rfbrondum** [comment]
The popup is made with "ShowModalDialog" which is not supported in  MS Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18235925/ , so this is not an error in the code, but we could investigate if there is an alternative. It seems to work in Chrome, IE and firefox, so we should still support most users.

**Comment by rfbrondum** [comment]
Works in MS edge, when hemaclass is started on a windows laptop, so it does not seem to be related to the link in the post above after all.  I have updated shiny-server to the newest version on the linux server, and the problem has disappeared.
