### ISSUE TITLE
Different classifications results

### ISSUE THREAD

**Issue by ghost** [CLINDA-AAU/hemaClass#6]
Get different classification results when doing the same classification locally and on the server.

**Comment by AEBilgrau** [comment]
For future reference, the current server version is the one in commit 437834c7857453937edf5370847f211b88927e49, correct?

**Comment by ghost** [comment]
Yes. But running that locally gives the same results as the new versions.

**Comment by falgreen** [comment]
It could be a problem with sorting. Windows and UNIX sorts differently.

**Comment by ghost** [comment]
Yes i think you are correct about the sorting. Changing lc_collate locally to match the server fixes the problem.

**Comment by AEBilgrau** [comment]
I'm not sure if I've understood correctly. But _why_ does sorting change the results? The methods shoud be invariant to the ordering of the ~~samples~~ probes. I find it quite concering.

**Comment by ghost** [comment]
I am not sure. But i think it has something to do with the order in which the probesets are arranged when you load them with readCelfiles(). 

If lc_collate is set to 'C' it orders the probesets like:
 A B C a b c
 And if lc_collate is set to UTF-8 it orders the probesets like:
A a B b C c

Does this explain it?

**Comment by falgreen** [comment]
Yes, it can explain it. However, It probably means that some place in the code there is an ordering of data according to the probesets. I Will take a look when I get home. 

Mvh Steffen

Sendt fra min iPhone

**Comment by ghost** [comment]
Okay thanks. I think the ordering is in the readCelfiles function, line 63 perhaps.

**Comment by AEBilgrau** [comment]
It seems to be the `userRMA` function which is to blame. It seems to rely on the reference and the supplied matrix are sorted in the same fashion.

**Comment by falgreen** [comment]
We should update this since we easily run in to problems. Right now you must use the same OS to create the reference as is used perform the classification.

**Comment by AEBilgrau** [comment]
Not in line 63. I think.
The heart of the problem can be reproduced by

``` R
library("hemaClass")

files <- list.files(system.file("extdata/celfiles", package = "hemaClass"), 
                    full.names = TRUE)
affy.batch1 <- readCelfiles(filenames = files) 
Sys.setlocale("LC_COLLATE", "C") 
affy.batch2 <- readCelfiles(filenames = files)

mapply(identical, affy.batch1, affy.batch2)
##     exprs  probesets    cdfname annotation 
##     FALSE      FALSE       TRUE       TRUE 
```

So it is [`affyio::read.celfile.probeintensity.matrices`](https://github.com/oncoclass/hemaClass/blob/master/R/readCelfiles.R#L69-L71) and [`affy::indexProbes`](https://github.com/oncoclass/hemaClass/blob/master/R/readCelfiles.R#L60) functions which appears to read in different orders.

The objects are equivalent however:

``` R
identical(affy.batch1$exprs[rownames(affy.batch2$exprs), ], 
          affy.batch2$exprs)
## TRUE

identical(affy.batch1$probesets[names(affy.batch2$probesets)],
          affy.batch2$probesets)
## TRUE
```

It's a bit troubling that the functions are not invariant to the order.

**Comment by falgreen** [comment]
I think I solved the problem in my latest commit, but I won't be able to test it before the weekend

**Comment by falgreen** [comment]
The problem occurred when building a reference using one sorting and using another sorting for the affy.batch. Try out the following code:

``` R
library("hemaClass")

files <- list.files(system.file("extdata/celfiles", package = "hemaClass"), 
                    full.names = TRUE)
affy.batch1 <- readCelfiles(filenames = files) 
rma.batch1 <- rmaPreprocessing(affy.batch1)
rma.batch1.ref1 <- rmaReference(affy.batch1, rma.batch1)


Sys.setlocale("LC_COLLATE", "C") 
affy.batch2 <- readCelfiles(filenames = files)
rma.batch2 <- rmaPreprocessing(affy.batch2)
rma.batch2.ref2 <- rmaReference(affy.batch2, rma.batch2)

rma.batch2.ref1 <- rmaReference(affy.batch2, rma.batch1)

identical(rma.batch1.ref1$exprs, 
          rma.batch2.ref2$exprs[rownames(rma.batch1.ref1$exprs), ]  )
## TRUE

identical(rma.batch1.ref1$exprs, 
          rma.batch2.ref1$exprs[rownames(rma.batch1.ref1$exprs), ]  )
## TRUE


identical(BAGS(rma.batch1.ref1$exprs.sc), BAGS(rma.batch2.ref2$exprs.sc))
## TRUE

identical(BAGS(rma.batch1.ref1$exprs.sc), BAGS(rma.batch2.ref1$exprs.sc))
## TRUE
```

**Comment by AEBilgrau** [comment]
That seems to fix it here :)

**Comment by mboegsted** [comment]
Is this issue closed then?

**Comment by falgreen** [comment]
Yes, this is solved!

**Comment by AEBilgrau** [comment]
Reopening issue. @falgreen your example fails on my computer. Have added some unit tests for the issue.

**Comment by falgreen** [comment]
I can see one part of the solution i posted have been reverted. I wiil add the solution again when i get home

**Comment by AEBilgrau** [comment]
Arh, I see. I think I'm responsible. I incorrectly resolved a merge conflict. Will try to add your solution again.
