### ISSUE TITLE
No true one-by-one normalisation available

### ISSUE THREAD

**Issue by AEBilgrau** [CLINDA-AAU/hemaClass#9]
You cannot actually select the true one by one RMA normalisation procedure on the website at the moment. This should be added!?

**Comment by falgreen** [comment]
What do you mean by true one-by-one? isn't the LLMPP CHOP reference available?

**Comment by AEBilgrau** [comment]
Yes. Blunder on my part. (Confused and remembering the old way we did it.)

Close #9.
